#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import eventlet
from eventlet import wsgi
eventlet.monkey_patch()

from app import create_app

if __name__ == '__main__':
    try:
        app = create_app(os.getenv('FLASK_CONFIG') or 'default')
        wsgi.server(eventlet.listen(('127.0.0.1', 54321)), app)
    except:
        raise
